namespace Clarity.Sage
{
    using System;

    public abstract class InvoiceHeaderProfile<TLine> : RecordProfile
        where TLine : InvoiceDetail
    {
        public InvoiceHeaderProfile()
        {
            EBMUserTypes ebmUserType;
            CreateMap<string[], InvoiceHeader<TLine>>()
                .IncludeAllDerived()
                .ForMember(dest => dest.InvoiceNo, opt => opt.MapFrom(src => src[6]))
                .ForMember(dest => dest.InvoiceDate, opt => opt.MapFrom(src => src[7].ToNonEmptyStringOrNull()))
                .ForMember(dest => dest.InvoiceType, opt => opt.MapFrom(src => src[8].ToNonEmptyStringOrNull()))
                .ForMember(dest => dest.SalesOrderNo, opt => opt.MapFrom(src => src[9].ToNonEmptyStringOrNull()))
                .ForMember(dest => dest.OrderType, opt => opt.MapFrom(src => src[10].ToNullableChar()))
                .ForMember(dest => dest.OrderStatus, opt => opt.MapFrom(src => src[11].ToNullableChar()))
                .ForMember(dest => dest.OrderDate, opt => opt.MapFrom(src => src[12].ToNonEmptyStringOrNull()))
                .ForMember(dest => dest.ARDivisionNo, opt => opt.MapFrom(src => src[13]))
                .ForMember(dest => dest.CustomerNo, opt => opt.MapFrom(src => src[14].ToNonEmptyStringOrNull()))
                .ForMember(dest => dest.BillToDivisionNo, opt => opt.MapFrom(src => src[15].ToNonEmptyStringOrNull()))
                .ForMember(dest => dest.BillToCustomerNo, opt => opt.MapFrom(src => src[16].ToNonEmptyStringOrNull()))
                .ForMember(dest => dest.BillToName, opt => opt.MapFrom(src => src[17].ToNonEmptyStringOrNull()))
                .ForMember(dest => dest.BillToAddress1, opt => opt.MapFrom(src => src[18].ToNonEmptyStringOrNull()))
                .ForMember(dest => dest.BillToAddress2, opt => opt.MapFrom(src => src[19].ToNonEmptyStringOrNull()))
                .ForMember(dest => dest.BillToAddress3, opt => opt.MapFrom(src => src[20].ToNonEmptyStringOrNull()))
                .ForMember(dest => dest.BillToCity, opt => opt.MapFrom(src => src[21].ToNonEmptyStringOrNull()))
                .ForMember(dest => dest.BillToState, opt => opt.MapFrom(src => src[22].ToNonEmptyStringOrNull()))
                .ForMember(dest => dest.BillToZipCode, opt => opt.MapFrom(src => src[23].ToNonEmptyStringOrNull()))
                .ForMember(dest => dest.BillToCountryCode, opt => opt.MapFrom(src => src[24].ToNonEmptyStringOrNull()))
                .ForMember(dest => dest.ShipToCode, opt => opt.MapFrom(src => src[25].ToNonEmptyStringOrNull()))
                .ForMember(dest => dest.ShipToName, opt => opt.MapFrom(src => src[26].ToNonEmptyStringOrNull()))
                .ForMember(dest => dest.ShipToAddress1, opt => opt.MapFrom(src => src[27].ToNonEmptyStringOrNull()))
                .ForMember(dest => dest.ShipToAddress2, opt => opt.MapFrom(src => src[28].ToNonEmptyStringOrNull()))
                .ForMember(dest => dest.ShipToAddress3, opt => opt.MapFrom(src => src[29].ToNonEmptyStringOrNull()))
                .ForMember(dest => dest.ShipToCity, opt => opt.MapFrom(src => src[30].ToNonEmptyStringOrNull()))
                .ForMember(dest => dest.ShipToState, opt => opt.MapFrom(src => src[31].ToNonEmptyStringOrNull()))
                .ForMember(dest => dest.ShipToZipCode, opt => opt.MapFrom(src => src[32].ToNonEmptyStringOrNull()))
                .ForMember(dest => dest.ShipToCountryCode, opt => opt.MapFrom(src => src[33].ToNonEmptyStringOrNull()))
                .ForMember(dest => dest.ShipDate, opt => opt.MapFrom(src => src[34].ToNonEmptyStringOrNull()))
                .ForMember(dest => dest.ShipVia, opt => opt.MapFrom(src => src[35].ToNonEmptyStringOrNull()))
                .ForMember(dest => dest.ShipZone, opt => opt.MapFrom(src => src[36].ToNonEmptyStringOrNull()))
                .ForMember(dest => dest.ShipZoneActual, opt => opt.MapFrom(src => src[37].ToNonEmptyStringOrNull()))
                .ForMember(dest => dest.ShipWeight, opt => opt.MapFrom(src => src[38].ToNonEmptyStringOrNull()))
                .ForMember(dest => dest.CustomerPONo, opt => opt.MapFrom(src => src[39].ToNonEmptyStringOrNull()))
                .ForMember(dest => dest.FOB, opt => opt.MapFrom(src => src[40].ToNonEmptyStringOrNull()))
                .ForMember(dest => dest.WarehouseCode, opt => opt.MapFrom(src => src[41].ToNonEmptyStringOrNull()))
                .ForMember(dest => dest.ConfirmTo, opt => opt.MapFrom(src => src[42].ToNonEmptyStringOrNull()))
                .ForMember(dest => dest.Comment, opt => opt.MapFrom(src => src[43].ToNonEmptyStringOrNull()))
                .ForMember(dest => dest.TaxSchedule, opt => opt.MapFrom(src => src[44].ToNonEmptyStringOrNull()))
                .ForMember(dest => dest.TermsCode, opt => opt.MapFrom(src => src[45].ToNonEmptyStringOrNull()))
                .ForMember(dest => dest.TaxExemptNo, opt => opt.MapFrom(src => src[46].ToNonEmptyStringOrNull()))
                .ForMember(dest => dest.PrintInvoice, opt => opt.MapFrom(src => src[47].ToNullableBool()))
                .ForMember(dest => dest.InvoicePrinted, opt => opt.MapFrom(src => src[48].ToNullableBool()))
                .ForMember(dest => dest.AcceptCashOnly, opt => opt.MapFrom(src => src[49].ToNullableBool()))
                .ForMember(dest => dest.CustomerType, opt => opt.MapFrom(src => src[50].ToNonEmptyStringOrNull()))
                .ForMember(dest => dest.ResidentialAddress, opt => opt.MapFrom(src => src[51].ToNullableBool()))
                .ForMember(dest => dest.InvalidTaxCalc, opt => opt.MapFrom(src => src[52].ToNullableBool()))
                .ForMember(dest => dest.FreightCalculationMethod, opt => opt.MapFrom(src => src[53].ToNullableChar()))
                .ForMember(dest => dest.CheckNoForDeposit, opt => opt.MapFrom(src => src[54].ToNonEmptyStringOrNull()))
                .ForMember(dest => dest.ApplyToInvoiceNo, opt => opt.MapFrom(src => src[55].ToNonEmptyStringOrNull()))
                .ForMember(dest => dest.LotSerialLinesExist, opt => opt.MapFrom(src => src[56].ToNullableBool()))
                .ForMember(dest => dest.SalespersonDivisionNo, opt => opt.MapFrom(src => src[57].ToNonEmptyStringOrNull()))
                .ForMember(dest => dest.SalespersonNo, opt => opt.MapFrom(src => src[58].ToNonEmptyStringOrNull()))
                .ForMember(dest => dest.SplitCommissions, opt => opt.MapFrom(src => src[59].ToNullableChar()))
                .ForMember(dest => dest.SalespersonDivisionNo2, opt => opt.MapFrom(src => src[60].ToNonEmptyStringOrNull()))
                .ForMember(dest => dest.SalespersonNo2, opt => opt.MapFrom(src => src[61].ToNonEmptyStringOrNull()))
                .ForMember(dest => dest.SalespersonDivisionNo3, opt => opt.MapFrom(src => src[62].ToNonEmptyStringOrNull()))
                .ForMember(dest => dest.SalespersonNo3, opt => opt.MapFrom(src => src[63].ToNonEmptyStringOrNull()))
                .ForMember(dest => dest.SalespersonDivisionNo4, opt => opt.MapFrom(src => src[64].ToNonEmptyStringOrNull()))
                .ForMember(dest => dest.SalespersonNo4, opt => opt.MapFrom(src => src[65].ToNonEmptyStringOrNull()))
                .ForMember(dest => dest.SalespersonDivisionNo5, opt => opt.MapFrom(src => src[66].ToNonEmptyStringOrNull()))
                .ForMember(dest => dest.SalespersonNo5, opt => opt.MapFrom(src => src[67].ToNonEmptyStringOrNull()))
                .ForMember(dest => dest.InvoiceDueDate, opt => opt.MapFrom(src => src[68].ToNonEmptyStringOrNull()))
                .ForMember(dest => dest.DiscountDueDate, opt => opt.MapFrom(src => src[69].ToNonEmptyStringOrNull()))
                .ForMember(dest => dest.BatchNo, opt => opt.MapFrom(src => src[70].ToNonEmptyStringOrNull()))
                .ForMember(dest => dest.EBMSubmissionType, opt => opt.MapFrom(src => src[71].ToNullableChar()))
                .ForMember(dest => dest.EBMUserIDSubmittingThisOrder, opt => opt.MapFrom(src => src[72].ToNonEmptyStringOrNull()))
                .ForMember(dest => dest.EBMUserType, opt => opt.MapFrom(src => Enum.TryParse(src[73], out ebmUserType) ? (EBMUserTypes?)ebmUserType : null))
                .ForMember(dest => dest.EMailUpdateFlagForRestart, opt => opt.MapFrom(src => src[74].ToNullableChar()))
                .ForMember(dest => dest.FaxNo, opt => opt.MapFrom(src => src[75].ToNonEmptyStringOrNull()))
                .ForMember(dest => dest.BatchFax, opt => opt.MapFrom(src => src[76].ToNullableBool()))
                .ForMember(dest => dest.BatchEmail, opt => opt.MapFrom(src => src[77].ToNullableBool()))
                .ForMember(dest => dest.EmailAddress, opt => opt.MapFrom(src => src[78].ToNonEmptyStringOrNull()))
                .ForMember(dest => dest.PaymentType, opt => opt.MapFrom(src => src[79].ToNonEmptyStringOrNull()))
                .ForMember(dest => dest.OtherPaymentTypeRefNo, opt => opt.MapFrom(src => src[80].ToNonEmptyStringOrNull()))
                .ForMember(dest => dest.PaymentTypeCategory, opt => opt.MapFrom(src => src[81].ToNonEmptyStringOrNull()))
                .ForMember(dest => dest.OrderChangedInShipping, opt => opt.MapFrom(src => src[82].ToNullableBool()))
                .ForMember(dest => dest.LinesChangedInShipping, opt => opt.MapFrom(src => src[83].ToNullableBool()))
                .ForMember(dest => dest.ShipperID, opt => opt.MapFrom(src => src[84].ToNonEmptyStringOrNull()))
                .ForMember(dest => dest.ShipStatus, opt => opt.MapFrom(src => src[85].ToNullableChar()))
                .ForMember(dest => dest.StarshipFreightUsed, opt => opt.MapFrom(src => src[86].ToNullableBool()))
                .ForMember(dest => dest.StarshipRecordsCreated, opt => opt.MapFrom(src => src[87].ToNullableBool()))
                .ForMember(dest => dest.JobNo, opt => opt.MapFrom(src => src[88].ToNonEmptyStringOrNull()))
                .ForMember(dest => dest.RMANo, opt => opt.MapFrom(src => src[89].ToNonEmptyStringOrNull()))
                .ForMember(dest => dest.CRMUserID, opt => opt.MapFrom(src => src[90].ToNonEmptyStringOrNull()))
                .ForMember(dest => dest.CRMCompanyID, opt => opt.MapFrom(src => src[91].ToNonEmptyStringOrNull()))
                .ForMember(dest => dest.CRMPersonID, opt => opt.MapFrom(src => src[92].ToNonEmptyStringOrNull()))
                .ForMember(dest => dest.CRMOpportunityID, opt => opt.MapFrom(src => src[93].ToNonEmptyStringOrNull()))
                .ForMember(dest => dest.InvalidWarrantyCode, opt => opt.MapFrom(src => src[94].ToNullableBool()))
                .ForMember(dest => dest.TaxableSubjectToDiscount, opt => opt.MapFrom(src => src[95].ToNullableDecimal()))
                .ForMember(dest => dest.NonTaxableSubjectToDiscount, opt => opt.MapFrom(src => src[96].ToNullableDecimal()))
                .ForMember(dest => dest.TaxSubjToDiscPrcntOfTotSubjTo, opt => opt.MapFrom(src => src[97].ToNullableDecimal()))
                .ForMember(dest => dest.DiscountRate, opt => opt.MapFrom(src => src[98].ToNullableDecimal()))
                .ForMember(dest => dest.TaxableAmt, opt => opt.MapFrom(src => src[99].ToNullableDecimal()))
                .ForMember(dest => dest.NonTaxableAmt, opt => opt.MapFrom(src => src[100].ToNullableDecimal()))
                .ForMember(dest => dest.SalesTaxAmt, opt => opt.MapFrom(src => src[101].ToNullableDecimal()))
                .ForMember(dest => dest.DiscountAmt, opt => opt.MapFrom(src => src[102].ToNullableDecimal()))
                .ForMember(dest => dest.RetentionAmt, opt => opt.MapFrom(src => src[103].ToNullableDecimal()))
                .ForMember(dest => dest.TotalSubjectToComm, opt => opt.MapFrom(src => src[104].ToNullableDecimal()))
                .ForMember(dest => dest.CommissionRate, opt => opt.MapFrom(src => src[105].ToNullableDecimal()))
                .ForMember(dest => dest.CommissionAmt, opt => opt.MapFrom(src => src[106].ToNullableDecimal()))
                .ForMember(dest => dest.SplitCommRate2, opt => opt.MapFrom(src => src[107].ToNullableDecimal()))
                .ForMember(dest => dest.SplitCommRate3, opt => opt.MapFrom(src => src[108].ToNullableDecimal()))
                .ForMember(dest => dest.SplitCommRate4, opt => opt.MapFrom(src => src[109].ToNullableDecimal()))
                .ForMember(dest => dest.SplitCommRate5, opt => opt.MapFrom(src => src[110].ToNullableDecimal()))
                .ForMember(dest => dest.OverrideCommAmt, opt => opt.MapFrom(src => src[111].ToNullableDecimal()))
                .ForMember(dest => dest.FreightAmt, opt => opt.MapFrom(src => src[112].ToNullableDecimal()))
                .ForMember(dest => dest.CostOfGoodsSoldAmt, opt => opt.MapFrom(src => src[113].ToNullableDecimal()))
                .ForMember(dest => dest.CostOfGoodsSoldSubjToComm, opt => opt.MapFrom(src => src[114].ToNullableDecimal()))
                .ForMember(dest => dest.DepositAmt, opt => opt.MapFrom(src => src[115].ToNullableDecimal()))
                .ForMember(dest => dest.Weight, opt => opt.MapFrom(src => src[116].ToNullableDecimal()))
                .ForMember(dest => dest.SIShippedLinesCOGS, opt => opt.MapFrom(src => src[117].ToNullableDecimal()))
                .ForMember(dest => dest.NumberOfCODLabels, opt => opt.MapFrom(src => src[118].ToNullableInt()))
                .ForMember(dest => dest.NumberOfBackOrderLines, opt => opt.MapFrom(src => src[119].ToNullableInt()))
                .ForMember(dest => dest.NumberOfShippingLabels, opt => opt.MapFrom(src => src[120].ToNullableInt()))
                .ForMember(dest => dest.LastNoOfShippingLabels, opt => opt.MapFrom(src => src[121].ToNullableInt()))
                .ForMember(dest => dest.NumberofPackages, opt => opt.MapFrom(src => src[122].ToNullableInt()))
                .ForMember(dest => dest.Lines, opt => opt.Ignore());
        }
    }
}
