namespace Clarity.Sage.Rdp
{
    using System;
    using AutoMapper;

    public class ItemProfile : Profile
    {
        public ItemProfile()
        {
            CreateMap<string[], Item>()
                .IncludeAllDerived()
                .ForMember(dest => dest.ItemCode, opt => opt.MapFrom(src => src[6]))
                .ForMember(dest => dest.ItemType, opt => opt.MapFrom(src => Enum.Parse(typeof(ItemTypes), src[7])))
                .ForMember(dest => dest.ItemCodeDesc, opt => opt.MapFrom(src => src[8].ToNonEmptyStringOrNull()))
                .ForMember(dest => dest.ExtendedDescriptionKey, opt => opt.MapFrom(src => src[9].ToNonEmptyStringOrNull()))
                .ForMember(dest => dest.UseInAR, opt => opt.MapFrom(src => char.Parse(src[10])))
                .ForMember(dest => dest.UseInSO, opt => opt.MapFrom(src => char.Parse(src[11])))
                .ForMember(dest => dest.UseInPO, opt => opt.MapFrom(src => char.Parse(src[12])))
                .ForMember(dest => dest.UseInBM, opt => opt.MapFrom(src => char.Parse(src[13])))
                .ForMember(dest => dest.CalculateCommission, opt => opt.MapFrom(src => char.Parse(src[14])))
                .ForMember(dest => dest.DropShip, opt => opt.MapFrom(src => char.Parse(src[15])))
                .ForMember(dest => dest.EBMEnabled, opt => opt.MapFrom(src => char.Parse(src[16])))
                .ForMember(dest => dest.AllowBackOrders, opt => opt.MapFrom(src => char.Parse(src[17])))
                .ForMember(dest => dest.AllowReturns, opt => opt.MapFrom(src => char.Parse(src[18])))
                .ForMember(dest => dest.PriceCode, opt => opt.MapFrom(src => src[19].ToNonEmptyStringOrNull()))
                .ForMember(dest => dest.AllowTradeDiscount, opt => opt.MapFrom(src => char.Parse(src[20])))
                .ForMember(dest => dest.PrintReceiptLabels, opt => opt.MapFrom(src => char.Parse(src[21])))
                .ForMember(dest => dest.AllocateLandedCost, opt => opt.MapFrom(src => char.Parse(src[22])))
                .ForMember(dest => dest.InactiveItem, opt => opt.MapFrom(src => char.Parse(src[23])))
                .ForMember(dest => dest.ConfirmCostIncrInRcptOfGoods, opt => opt.MapFrom(src => char.Parse(src[24])))
                .ForMember(dest => dest.WarrantyCode, opt => opt.MapFrom(src => src[25].ToNonEmptyStringOrNull()))
                .ForMember(dest => dest.SalesUnitOfMeasure, opt => opt.MapFrom(src => src[26].ToNonEmptyStringOrNull()))
                .ForMember(dest => dest.PurchaseUnitOfMeasure, opt => opt.MapFrom(src => src[27].ToNonEmptyStringOrNull()))
                .ForMember(dest => dest.StandardUnitOfMeasure, opt => opt.MapFrom(src => src[28].ToNonEmptyStringOrNull()))
                .ForMember(dest => dest.PostToGLByDivision, opt => opt.MapFrom(src => char.Parse(src[29])))
                .ForMember(dest => dest.SalesAcctKey, opt => opt.MapFrom(src => src[30].ToNonEmptyStringOrNull()))
                .ForMember(dest => dest.CostOfGoodsSoldAcctKey, opt => opt.MapFrom(src => src[31].ToNonEmptyStringOrNull()))
                .ForMember(dest => dest.InventoryAcctKey, opt => opt.MapFrom(src => src[32].ToNonEmptyStringOrNull()))
                .ForMember(dest => dest.PurchaseAcctKey, opt => opt.MapFrom(src => src[33].ToNonEmptyStringOrNull()))
                .ForMember(dest => dest.ManufacturingCostAcctKey, opt => opt.MapFrom(src => src[34].ToNonEmptyStringOrNull()))
                .ForMember(dest => dest.TaxClass, opt => opt.MapFrom(src => src[35].ToNonEmptyStringOrNull()))
                .ForMember(dest => dest.PurchasesTaxClass, opt => opt.MapFrom(src => src[36].ToNonEmptyStringOrNull()))
                .ForMember(dest => dest.ProductLine, opt => opt.MapFrom(src => src[37].ToNonEmptyStringOrNull()))
                .ForMember(dest => dest.ProductType, opt => opt.MapFrom(src => char.Parse(src[38])))
                .ForMember(dest => dest.Valuation, opt => opt.MapFrom(src => char.Parse(src[39])))
                .ForMember(dest => dest.DefaultWarehouseCode, opt => opt.MapFrom(src => src[40].ToNonEmptyStringOrNull()))
                .ForMember(dest => dest.PrimaryAPDivisionNo, opt => opt.MapFrom(src => src[41].ToNonEmptyStringOrNull()))
                .ForMember(dest => dest.PrimaryVendorNo, opt => opt.MapFrom(src => src[42].ToNonEmptyStringOrNull()))
                .ForMember(dest => dest.ImageFile, opt => opt.MapFrom(src => src[43].ToNonEmptyStringOrNull()))
                .ForMember(dest => dest.LastSoldDate, opt => opt.MapFrom(src => src[44].ToNonEmptyStringOrNull()))
                .ForMember(dest => dest.LastReceiptDate, opt => opt.MapFrom(src => src[45].ToNonEmptyStringOrNull()))
                .ForMember(dest => dest.Category1, opt => opt.MapFrom(src => src[46].ToNonEmptyStringOrNull()))
                .ForMember(dest => dest.Category2, opt => opt.MapFrom(src => src[47].ToNonEmptyStringOrNull()))
                .ForMember(dest => dest.Category3, opt => opt.MapFrom(src => src[48].ToNonEmptyStringOrNull()))
                .ForMember(dest => dest.Category4, opt => opt.MapFrom(src => src[49].ToNonEmptyStringOrNull()))
                .ForMember(dest => dest.SalesPromotionCode, opt => opt.MapFrom(src => src[50].ToNonEmptyStringOrNull()))
                .ForMember(dest => dest.SaleStartingDate, opt => opt.MapFrom(src => src[51].ToNonEmptyStringOrNull()))
                .ForMember(dest => dest.SaleEndingDate, opt => opt.MapFrom(src => src[52].ToNonEmptyStringOrNull()))
                .ForMember(dest => dest.SaleMethod, opt => opt.MapFrom(src => char.Parse(src[53])))
                .ForMember(dest => dest.ExplodeKitItems, opt => opt.MapFrom(src => char.Parse(src[54])))
                .ForMember(dest => dest.ShipWeight, opt => opt.MapFrom(src => src[55].ToNonEmptyStringOrNull()))
                .ForMember(dest => dest.CommentText, opt => opt.MapFrom(src => src[56].ToNonEmptyStringOrNull()))
                .ForMember(dest => dest.RestockingMethod, opt => opt.MapFrom(src => char.Parse(src[57])))
                .ForMember(dest => dest.NextLotSerialNo, opt => opt.MapFrom(src => src[58].ToNonEmptyStringOrNull()))
                .ForMember(dest => dest.InventoryCycle, opt => opt.MapFrom(src => src[59].ToNullableChar()))
                .ForMember(dest => dest.RoutingNo, opt => opt.MapFrom(src => src[60].ToNonEmptyStringOrNull()))
                .ForMember(dest => dest.ProcurementType, opt => opt.MapFrom(src => char.Parse(src[61])))
                .ForMember(dest => dest.PlannerCode, opt => opt.MapFrom(src => src[62].ToNonEmptyStringOrNull()))
                .ForMember(dest => dest.BuyerCode, opt => opt.MapFrom(src => src[63].ToNonEmptyStringOrNull()))
                .ForMember(dest => dest.LowLevelCode, opt => opt.MapFrom(src => src[64].ToNonEmptyStringOrNull()))
                .ForMember(dest => dest.PlannedByMRP, opt => opt.MapFrom(src => char.Parse(src[65])))
                .ForMember(dest => dest.VendorItemCode, opt => opt.MapFrom(src => src[66].ToNonEmptyStringOrNull()))
                .ForMember(dest => dest.SetupCharge, opt => opt.MapFrom(src => char.Parse(src[67])))
                .ForMember(dest => dest.AttachmentFileName, opt => opt.MapFrom(src => src[68].ToNonEmptyStringOrNull()))
                .ForMember(dest => dest.ItemImageWidthInPixels, opt => opt.MapFrom(src => src[69].ToNullableInt()))
                .ForMember(dest => dest.ItemImageHeightInPixels, opt => opt.MapFrom(src => src[70].ToNullableInt()))
                .ForMember(dest => dest.StandardUnitCost, opt => opt.MapFrom(src => src[71].ToNullableDecimal()))
                .ForMember(dest => dest.StandardUnitPrice, opt => opt.MapFrom(src => src[72].ToNullableDecimal()))
                .ForMember(dest => dest.LastTotalUnitCost, opt => opt.MapFrom(src => src[73].ToNullableDecimal()))
                .ForMember(dest => dest.AverageUnitCost, opt => opt.MapFrom(src => src[74].ToNullableDecimal()))
                .ForMember(dest => dest.SalesPromotionPrice, opt => opt.MapFrom(src => src[75].ToNullableDecimal()))
                .ForMember(dest => dest.SuggestedRetailPrice, opt => opt.MapFrom(src => src[76].ToNullableDecimal()))
                .ForMember(dest => dest.SalesPromotionDiscountPercent, opt => opt.MapFrom(src => src[77].ToNullableDecimal()))
                .ForMember(dest => dest.TotalQuantityOnHand, opt => opt.MapFrom(src => src[78].ToNullableDecimal()))
                .ForMember(dest => dest.AverageBackOrderFillDays, opt => opt.MapFrom(src => src[79].ToNullableInt()))
                .ForMember(dest => dest.LastAllocatedUnitCost, opt => opt.MapFrom(src => src[80].ToNullableDecimal()))
                .ForMember(dest => dest.CommissionRate, opt => opt.MapFrom(src => src[81].ToNullableDecimal()))
                .ForMember(dest => dest.BaseCommAmt, opt => opt.MapFrom(src => src[82].ToNullableDecimal()))
                .ForMember(dest => dest.PurchaseUMConvFctr, opt => opt.MapFrom(src => src[83].ToNullableDecimal()))
                .ForMember(dest => dest.SalesUMConvFctr, opt => opt.MapFrom(src => src[84].ToNullableDecimal()))
                .ForMember(dest => dest.Volume, opt => opt.MapFrom(src => src[85].ToNullableDecimal()))
                .ForMember(dest => dest.RestockingCharge, opt => opt.MapFrom(src => src[86].ToNullableDecimal()))
                .ForMember(dest => dest.TotalInventoryValue, opt => opt.MapFrom(src => src[87].ToNullableDecimal()));
        }
    }
}
