namespace Clarity.Sage
{
    public abstract class SalesOrderHeaderProfile<TLine> : RecordProfile
        where TLine : SalesOrderDetail
    {
        public SalesOrderHeaderProfile()
        {
            CreateMap<string[], SalesOrderHeader<TLine>>()
                .IncludeAllDerived()
                .ForMember(dest => dest.SalesOrderNo, opt => opt.MapFrom(src => src[6]))
                .ForMember(dest => dest.OrderDate, opt => opt.MapFrom(src => src[7].ToNonEmptyStringOrNull()))
                .ForMember(dest => dest.OrderType, opt => opt.MapFrom(src => src[8].ToNullableChar()))
                .ForMember(dest => dest.OrderStatus, opt => opt.MapFrom(src => src[9].ToNullableChar()))
                .ForMember(dest => dest.MasterRepeatingOrderNo, opt => opt.MapFrom(src => src[10].ToNonEmptyStringOrNull()))
                .ForMember(dest => dest.ShipExpireDate, opt => opt.MapFrom(src => src[11].ToNonEmptyStringOrNull()))
                .ForMember(dest => dest.ARDivisionNo, opt => opt.MapFrom(src => src[12]))
                .ForMember(dest => dest.CustomerNo, opt => opt.MapFrom(src => src[13]))
                .ForMember(dest => dest.BillToDivisionNo, opt => opt.MapFrom(src => src[14].ToNonEmptyStringOrNull()))
                .ForMember(dest => dest.BillToCustomerNo, opt => opt.MapFrom(src => src[15].ToNonEmptyStringOrNull()))
                .ForMember(dest => dest.BillToName, opt => opt.MapFrom(src => src[16].ToNonEmptyStringOrNull()))
                .ForMember(dest => dest.BillToAddress1, opt => opt.MapFrom(src => src[17].ToNonEmptyStringOrNull()))
                .ForMember(dest => dest.BillToAddress2, opt => opt.MapFrom(src => src[18].ToNonEmptyStringOrNull()))
                .ForMember(dest => dest.BillToAddress3, opt => opt.MapFrom(src => src[19].ToNonEmptyStringOrNull()))
                .ForMember(dest => dest.BillToCity, opt => opt.MapFrom(src => src[20].ToNonEmptyStringOrNull()))
                .ForMember(dest => dest.BillToState, opt => opt.MapFrom(src => src[21].ToNonEmptyStringOrNull()))
                .ForMember(dest => dest.BillToZipCode, opt => opt.MapFrom(src => src[22].ToNonEmptyStringOrNull()))
                .ForMember(dest => dest.BillToCountryCode, opt => opt.MapFrom(src => src[23].ToNonEmptyStringOrNull()))
                .ForMember(dest => dest.ShipToCode, opt => opt.MapFrom(src => src[24].ToNonEmptyStringOrNull()))
                .ForMember(dest => dest.ShipToName, opt => opt.MapFrom(src => src[25].ToNonEmptyStringOrNull()))
                .ForMember(dest => dest.ShipToAddress1, opt => opt.MapFrom(src => src[26].ToNonEmptyStringOrNull()))
                .ForMember(dest => dest.ShipToAddress2, opt => opt.MapFrom(src => src[27].ToNonEmptyStringOrNull()))
                .ForMember(dest => dest.ShipToAddress3, opt => opt.MapFrom(src => src[28].ToNonEmptyStringOrNull()))
                .ForMember(dest => dest.ShipToCity, opt => opt.MapFrom(src => src[29].ToNonEmptyStringOrNull()))
                .ForMember(dest => dest.ShipToState, opt => opt.MapFrom(src => src[30].ToNonEmptyStringOrNull()))
                .ForMember(dest => dest.ShipToZipCode, opt => opt.MapFrom(src => src[31].ToNonEmptyStringOrNull()))
                .ForMember(dest => dest.ShipToCountryCode, opt => opt.MapFrom(src => src[32].ToNonEmptyStringOrNull()))
                .ForMember(dest => dest.ShipVia, opt => opt.MapFrom(src => src[33].ToNonEmptyStringOrNull()))
                .ForMember(dest => dest.ShipZone, opt => opt.MapFrom(src => src[34].ToNonEmptyStringOrNull()))
                .ForMember(dest => dest.ShipZoneActual, opt => opt.MapFrom(src => src[35].ToNonEmptyStringOrNull()))
                .ForMember(dest => dest.ShipWeight, opt => opt.MapFrom(src => src[36].ToNonEmptyStringOrNull()))
                .ForMember(dest => dest.CustomerPONo, opt => opt.MapFrom(src => src[37].ToNonEmptyStringOrNull()))
                .ForMember(dest => dest.FOB, opt => opt.MapFrom(src => src[38].ToNonEmptyStringOrNull()))
                .ForMember(dest => dest.WarehouseCode, opt => opt.MapFrom(src => src[39].ToNonEmptyStringOrNull()))
                .ForMember(dest => dest.ConfirmTo, opt => opt.MapFrom(src => src[40].ToNonEmptyStringOrNull()))
                .ForMember(dest => dest.Comment, opt => opt.MapFrom(src => src[41].ToNonEmptyStringOrNull()))
                .ForMember(dest => dest.TermsCode, opt => opt.MapFrom(src => src[42].ToNonEmptyStringOrNull()))
                .ForMember(dest => dest.TaxSchedule, opt => opt.MapFrom(src => src[43].ToNonEmptyStringOrNull()))
                .ForMember(dest => dest.TaxExemptNo, opt => opt.MapFrom(src => src[44].ToNonEmptyStringOrNull()))
                .ForMember(dest => dest.InvalidTaxCalc, opt => opt.MapFrom(src => src[45].ToNullableChar()))
                .ForMember(dest => dest.PrintSalesOrders, opt => opt.MapFrom(src => src[46].ToNullableChar()))
                .ForMember(dest => dest.SalesOrderPrinted, opt => opt.MapFrom(src => src[47].ToNullableChar()))
                .ForMember(dest => dest.PrintPickingSheets, opt => opt.MapFrom(src => src[48].ToNullableChar()))
                .ForMember(dest => dest.PickingSheetPrinted, opt => opt.MapFrom(src => src[49].ToNullableChar()))
                .ForMember(dest => dest.LastInvoiceOrderDate, opt => opt.MapFrom(src => src[50].ToNonEmptyStringOrNull()))
                .ForMember(dest => dest.LastInvoiceOrderNo, opt => opt.MapFrom(src => src[51].ToNonEmptyStringOrNull()))
                .ForMember(dest => dest.CurrentInvoiceNo, opt => opt.MapFrom(src => src[52].ToNonEmptyStringOrNull()))
                .ForMember(dest => dest.CheckNoForDeposit, opt => opt.MapFrom(src => src[53].ToNonEmptyStringOrNull()))
                .ForMember(dest => dest.CycleCode, opt => opt.MapFrom(src => src[54].ToNonEmptyStringOrNull()))
                .ForMember(dest => dest.FaxNo, opt => opt.MapFrom(src => src[55].ToNonEmptyStringOrNull()))
                .ForMember(dest => dest.BatchFax, opt => opt.MapFrom(src => src[56].ToNullableChar()))
                .ForMember(dest => dest.BatchEmail, opt => opt.MapFrom(src => src[57].ToNullableChar()))
                .ForMember(dest => dest.EmailAddress, opt => opt.MapFrom(src => src[58].ToNonEmptyStringOrNull()))
                .ForMember(dest => dest.FreightCalculationMethod, opt => opt.MapFrom(src => src[59].ToNullableChar()))
                .ForMember(dest => dest.LotSerialLinesExist, opt => opt.MapFrom(src => src[60].ToNullableChar()))
                .ForMember(dest => dest.SalespersonDivisionNo, opt => opt.MapFrom(src => src[61].ToNonEmptyStringOrNull()))
                .ForMember(dest => dest.SalespersonNo, opt => opt.MapFrom(src => src[62].ToNonEmptyStringOrNull()))
                .ForMember(dest => dest.SplitCommissions, opt => opt.MapFrom(src => src[63].ToNullableChar()))
                .ForMember(dest => dest.SalespersonDivisionNo2, opt => opt.MapFrom(src => src[64].ToNonEmptyStringOrNull()))
                .ForMember(dest => dest.SalespersonNo2, opt => opt.MapFrom(src => src[65].ToNonEmptyStringOrNull()))
                .ForMember(dest => dest.SalespersonDivisionNo3, opt => opt.MapFrom(src => src[66].ToNonEmptyStringOrNull()))
                .ForMember(dest => dest.SalespersonNo3, opt => opt.MapFrom(src => src[67].ToNonEmptyStringOrNull()))
                .ForMember(dest => dest.SalespersonDivisionNo4, opt => opt.MapFrom(src => src[68].ToNonEmptyStringOrNull()))
                .ForMember(dest => dest.SalespersonNo4, opt => opt.MapFrom(src => src[69].ToNonEmptyStringOrNull()))
                .ForMember(dest => dest.SalespersonDivisionNo5, opt => opt.MapFrom(src => src[70].ToNonEmptyStringOrNull()))
                .ForMember(dest => dest.SalespersonNo5, opt => opt.MapFrom(src => src[71].ToNonEmptyStringOrNull()))
                .ForMember(dest => dest.EBMUserType, opt => opt.MapFrom(src => src[72].ToNullableChar()))
                .ForMember(dest => dest.EBMSubmissionType, opt => opt.MapFrom(src => src[73].ToNullableChar()))
                .ForMember(dest => dest.EBMUserIDSubmittingThisOrder, opt => opt.MapFrom(src => src[74].ToNonEmptyStringOrNull()))
                .ForMember(dest => dest.PaymentType, opt => opt.MapFrom(src => src[75].ToNonEmptyStringOrNull()))
                .ForMember(dest => dest.OtherPaymentTypeRefNo, opt => opt.MapFrom(src => src[76].ToNonEmptyStringOrNull()))
                .ForMember(dest => dest.PaymentTypeCategory, opt => opt.MapFrom(src => src[77].ToNullableChar()))
                .ForMember(dest => dest.CancelReasonCode, opt => opt.MapFrom(src => src[78].ToNonEmptyStringOrNull()))
                .ForMember(dest => dest.RMANo, opt => opt.MapFrom(src => src[79].ToNonEmptyStringOrNull()))
                .ForMember(dest => dest.JobNo, opt => opt.MapFrom(src => src[80].ToNonEmptyStringOrNull()))
                .ForMember(dest => dest.ResidentialAddress, opt => opt.MapFrom(src => src[81].ToNullableChar()))
                .ForMember(dest => dest.CRMUserID, opt => opt.MapFrom(src => src[82].ToNonEmptyStringOrNull()))
                .ForMember(dest => dest.CRMPersonID, opt => opt.MapFrom(src => src[83].ToNonEmptyStringOrNull()))
                .ForMember(dest => dest.CRMOpportunityID, opt => opt.MapFrom(src => src[84].ToNonEmptyStringOrNull()))
                .ForMember(dest => dest.CRMCompanyID, opt => opt.MapFrom(src => src[85].ToNonEmptyStringOrNull()))
                .ForMember(dest => dest.CRMProspectID, opt => opt.MapFrom(src => src[86].ToNonEmptyStringOrNull()))
                .ForMember(dest => dest.TaxableSubjectToDiscount, opt => opt.MapFrom(src => src[87].ToNullableDecimal()))
                .ForMember(dest => dest.NonTaxableSubjectToDiscount, opt => opt.MapFrom(src => src[88].ToNullableDecimal()))
                .ForMember(dest => dest.TaxSubjToDiscPrcntOfTotSubjTo, opt => opt.MapFrom(src => src[89].ToNullableDecimal()))
                .ForMember(dest => dest.DiscountRate, opt => opt.MapFrom(src => src[90].ToNullableDecimal()))
                .ForMember(dest => dest.DiscountAmt, opt => opt.MapFrom(src => src[91].ToNullableDecimal()))
                .ForMember(dest => dest.TaxableAmt, opt => opt.MapFrom(src => src[92].ToNullableDecimal()))
                .ForMember(dest => dest.NonTaxableAmt, opt => opt.MapFrom(src => src[93].ToNullableDecimal()))
                .ForMember(dest => dest.SalesTaxAmt, opt => opt.MapFrom(src => src[94].ToNullableDecimal()))
                .ForMember(dest => dest.Weight, opt => opt.MapFrom(src => src[95].ToNullableDecimal()))
                .ForMember(dest => dest.FreightAmt, opt => opt.MapFrom(src => src[96].ToNullableDecimal()))
                .ForMember(dest => dest.DepositAmt, opt => opt.MapFrom(src => src[97].ToNullableDecimal()))
                .ForMember(dest => dest.CommissionRate, opt => opt.MapFrom(src => src[98].ToNullableDecimal()))
                .ForMember(dest => dest.SplitCommRate2, opt => opt.MapFrom(src => src[99].ToNullableDecimal()))
                .ForMember(dest => dest.SplitCommRate3, opt => opt.MapFrom(src => src[100].ToNullableDecimal()))
                .ForMember(dest => dest.SplitCommRate4, opt => opt.MapFrom(src => src[101].ToNullableDecimal()))
                .ForMember(dest => dest.SplitCommRate5, opt => opt.MapFrom(src => src[102].ToNullableDecimal()))
                .ForMember(dest => dest.NumberOfShippingLabels, opt => opt.MapFrom(src => src[103].ToNullableInt()))
                .ForMember(dest => dest.LastNoOfShippingLabels, opt => opt.MapFrom(src => src[104].ToNullableInt()))
                .ForMember(dest => dest.Lines, opt => opt.Ignore());
        }
    }
}
