namespace crgolden.Sage100
{
    public abstract class SalesOrderHistoryHeaderProfile<TLine> : RecordProfile
        where TLine : SalesOrderHistoryDetail
    {
        public SalesOrderHistoryHeaderProfile()
        {
            CreateMap<string[], SalesOrderHistoryHeader<TLine>>()
                .IncludeAllDerived()
                .ForMember(dest => dest.SalesOrderNo, opt => opt.MapFrom(src => src[6]))
                .ForMember(dest => dest.OrderDate, opt => opt.MapFrom(src => src[7]))
                .ForMember(dest => dest.OrderStatus, opt => opt.MapFrom(src => src[8]))
                .ForMember(dest => dest.MasterRepeatingOrderNo, opt => opt.MapFrom(src => src[9]))
                .ForMember(dest => dest.ARDivisionNo, opt => opt.MapFrom(src => src[10]))
                .ForMember(dest => dest.CustomerNo, opt => opt.MapFrom(src => src[11]))
                .ForMember(dest => dest.BillToDivisionNo, opt => opt.MapFrom(src => src[12]))
                .ForMember(dest => dest.BillToCustomerNo, opt => opt.MapFrom(src => src[13]))
                .ForMember(dest => dest.BillToName, opt => opt.MapFrom(src => src[14]))
                .ForMember(dest => dest.BillToAddress1, opt => opt.MapFrom(src => src[15]))
                .ForMember(dest => dest.BillToAddress2, opt => opt.MapFrom(src => src[16]))
                .ForMember(dest => dest.BillToAddress3, opt => opt.MapFrom(src => src[17]))
                .ForMember(dest => dest.BillToCity, opt => opt.MapFrom(src => src[18]))
                .ForMember(dest => dest.BillToState, opt => opt.MapFrom(src => src[19]))
                .ForMember(dest => dest.BillToZipCode, opt => opt.MapFrom(src => src[20]))
                .ForMember(dest => dest.BillToCountryCode, opt => opt.MapFrom(src => src[21]))
                .ForMember(dest => dest.ShipToCode, opt => opt.MapFrom(src => src[22]))
                .ForMember(dest => dest.ShipToName, opt => opt.MapFrom(src => src[23]))
                .ForMember(dest => dest.ShipToAddress1, opt => opt.MapFrom(src => src[24]))
                .ForMember(dest => dest.ShipToAddress2, opt => opt.MapFrom(src => src[25]))
                .ForMember(dest => dest.ShipToAddress3, opt => opt.MapFrom(src => src[26]))
                .ForMember(dest => dest.ShipToCity, opt => opt.MapFrom(src => src[27]))
                .ForMember(dest => dest.ShipToState, opt => opt.MapFrom(src => src[28]))
                .ForMember(dest => dest.ShipToZipCode, opt => opt.MapFrom(src => src[29]))
                .ForMember(dest => dest.ShipToCountryCode, opt => opt.MapFrom(src => src[30]))
                .ForMember(dest => dest.ShipVia, opt => opt.MapFrom(src => src[31]))
                .ForMember(dest => dest.ShipZone, opt => opt.MapFrom(src => src[32]))
                .ForMember(dest => dest.ShipZoneActual, opt => opt.MapFrom(src => src[33]))
                .ForMember(dest => dest.ShipWeight, opt => opt.MapFrom(src => src[34]))
                .ForMember(dest => dest.CustomerPONo, opt => opt.MapFrom(src => src[35]))
                .ForMember(dest => dest.EmailAddress, opt => opt.MapFrom(src => src[36]))
                .ForMember(dest => dest.ResidentialAddress, opt => opt.MapFrom(src => src[37]))
                .ForMember(dest => dest.CancelReasonCode, opt => opt.MapFrom(src => src[38]))
                .ForMember(dest => dest.FreightCalculationMethod, opt => opt.MapFrom(src => src[39]))
                .ForMember(dest => dest.FOB, opt => opt.MapFrom(src => src[40]))
                .ForMember(dest => dest.WarehouseCode, opt => opt.MapFrom(src => src[41]))
                .ForMember(dest => dest.ConfirmTo, opt => opt.MapFrom(src => src[42]))
                .ForMember(dest => dest.Comment, opt => opt.MapFrom(src => src[43]))
                .ForMember(dest => dest.TaxSchedule, opt => opt.MapFrom(src => src[44]))
                .ForMember(dest => dest.TermsCode, opt => opt.MapFrom(src => src[45]))
                .ForMember(dest => dest.TaxExemptNo, opt => opt.MapFrom(src => src[46]))
                .ForMember(dest => dest.RMANo, opt => opt.MapFrom(src => src[47]))
                .ForMember(dest => dest.JobNo, opt => opt.MapFrom(src => src[48]))
                .ForMember(dest => dest.LastInvoiceDate, opt => opt.MapFrom(src => src[49]))
                .ForMember(dest => dest.LastInvoiceNo, opt => opt.MapFrom(src => src[50]))
                .ForMember(dest => dest.CheckNoForDeposit, opt => opt.MapFrom(src => src[51]))
                .ForMember(dest => dest.LotSerialLinesExist, opt => opt.MapFrom(src => src[52]))
                .ForMember(dest => dest.SalespersonDivisionNo, opt => opt.MapFrom(src => src[53]))
                .ForMember(dest => dest.SalespersonNo, opt => opt.MapFrom(src => src[54]))
                .ForMember(dest => dest.SplitCommissions, opt => opt.MapFrom(src => src[55]))
                .ForMember(dest => dest.SalespersonDivisionNo2, opt => opt.MapFrom(src => src[56]))
                .ForMember(dest => dest.SalespersonNo2, opt => opt.MapFrom(src => src[57]))
                .ForMember(dest => dest.SalespersonDivisionNo3, opt => opt.MapFrom(src => src[58]))
                .ForMember(dest => dest.SalespersonNo3, opt => opt.MapFrom(src => src[59]))
                .ForMember(dest => dest.SalespersonDivisionNo4, opt => opt.MapFrom(src => src[60]))
                .ForMember(dest => dest.SalespersonNo4, opt => opt.MapFrom(src => src[61]))
                .ForMember(dest => dest.SalespersonDivisionNo5, opt => opt.MapFrom(src => src[62]))
                .ForMember(dest => dest.SalespersonNo5, opt => opt.MapFrom(src => src[63]))
                .ForMember(dest => dest.EBMUserType, opt => opt.MapFrom(src => src[64]))
                .ForMember(dest => dest.EBMSubmissionType, opt => opt.MapFrom(src => src[65]))
                .ForMember(dest => dest.EBMUserIDSubmittingThisOrder, opt => opt.MapFrom(src => src[66]))
                .ForMember(dest => dest.PaymentType, opt => opt.MapFrom(src => src[67]))
                .ForMember(dest => dest.OtherPaymentTypeRefNo, opt => opt.MapFrom(src => src[68]))
                .ForMember(dest => dest.PaymentTypeCategory, opt => opt.MapFrom(src => src[69]))
                .ForMember(dest => dest.FaxNo, opt => opt.MapFrom(src => src[70]))
                .ForMember(dest => dest.CRMUserID, opt => opt.MapFrom(src => src[71]))
                .ForMember(dest => dest.CRMCompanyID, opt => opt.MapFrom(src => src[72]))
                .ForMember(dest => dest.CRMPersonID, opt => opt.MapFrom(src => src[73]))
                .ForMember(dest => dest.CRMOpportunityID, opt => opt.MapFrom(src => src[74]))
                .ForMember(dest => dest.PromotedDate, opt => opt.MapFrom(src => src[75]))
                .ForMember(dest => dest.TaxableSubjectToDiscount, opt => opt.MapFrom(src => src[76].ToNullableDecimal()))
                .ForMember(dest => dest.NonTaxableSubjectToDiscount, opt => opt.MapFrom(src => src[77].ToNullableDecimal()))
                .ForMember(dest => dest.TaxSubjToDiscPrcntOfTotSubjTo, opt => opt.MapFrom(src => src[78].ToNullableDecimal()))
                .ForMember(dest => dest.DiscountRate, opt => opt.MapFrom(src => src[79].ToNullableDecimal()))
                .ForMember(dest => dest.DiscountAmt, opt => opt.MapFrom(src => src[80].ToNullableDecimal()))
                .ForMember(dest => dest.TaxableAmt, opt => opt.MapFrom(src => src[81].ToNullableDecimal()))
                .ForMember(dest => dest.NonTaxableAmt, opt => opt.MapFrom(src => src[82].ToNullableDecimal()))
                .ForMember(dest => dest.SalesTaxAmt, opt => opt.MapFrom(src => src[83].ToNullableDecimal()))
                .ForMember(dest => dest.CommissionRate, opt => opt.MapFrom(src => src[84].ToNullableDecimal()))
                .ForMember(dest => dest.SplitCommRate2, opt => opt.MapFrom(src => src[85].ToNullableDecimal()))
                .ForMember(dest => dest.SplitCommRate3, opt => opt.MapFrom(src => src[86].ToNullableDecimal()))
                .ForMember(dest => dest.SplitCommRate4, opt => opt.MapFrom(src => src[87].ToNullableDecimal()))
                .ForMember(dest => dest.SplitCommRate5, opt => opt.MapFrom(src => src[88].ToNullableDecimal()))
                .ForMember(dest => dest.Weight, opt => opt.MapFrom(src => src[89].ToNullableDecimal()))
                .ForMember(dest => dest.FreightAmt, opt => opt.MapFrom(src => src[90].ToNullableDecimal()))
                .ForMember(dest => dest.DepositAmt, opt => opt.MapFrom(src => src[91].ToNullableDecimal()))
                .ForMember(dest => dest.InvoicedAmt, opt => opt.MapFrom(src => src[92].ToNullableDecimal()))
                .ForMember(dest => dest.Lines, opt => opt.Ignore())
                .ForAllOtherMembers(opt => opt.Ignore());
        }
    }
}
